# Generated by Django 6.0.5 on 2026-05-07 14:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('password2', models.CharField(default='', max_length=100)),
                ('rank_value', models.IntegerField(blank=True, null=True)),
                ('rank_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'my-user',
            },
        ),
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'my-user_rank',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='videos/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posture', models.CharField(default='', max_length=100)),
                ('rank_value', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='posture.usermodel')),
            ],
            options={
                'db_table': 'my-rank_history',
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_ranks',
            field=models.ManyToManyField(related_name='users', to='posture.userrank'),
        ),
        migrations.CreateModel(
            name='RankScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='posture.userrank')),
            ],
            options={
                'db_table': 'my-rank_scores',
            },
        ),
    ]
